export const ActionTypes = {
  SET_CHARACTERS: "SET_CHARACTERS",
  SELECTED_CHARACTERS: "SELECTED_CHARACTERS",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  CREATE_LOCATIONS: "CREATE_LOCATIONS",
};
